### ISSUE TITLE
sightglass-next build process downloads WASI SDK many times

### ISSUE THREAD

**Issue by cfallin** [bytecodealliance/sightglass#101]
While watching the output of `benchmarks-next/build.sh` scroll by, I noticed that it seems that every individual benchmark build is reconstructing a Docker image from scratch, including a download of the 48MB WASI SDK tarball as well as a number of Ubuntu packages. This is somewhat wasteful (bandwidth is not free) and also means the build is slower than it could be.

Could we consider building a base Docker image once and then using it to build each benchmark in turn?

**Comment by abrown** [comment]
Yup, I agree with this. I just was watching the same download output over and over and thought the same thing. Do you have a recommendation for naming the images?

**Comment by cfallin** [comment]
> Do you have a recommendation for naming the images?

Hmm, not sure -- if we have to use a tag, maybe something unlikely to cause a collision, like `sightglass-build-image-<git-commit>`. Otherwise IIUC it's possible to get the Docker hash as a result from `docker build` and use that directly?
