### ISSUE TITLE
Provide option to collect JSON output in separate file

### ISSUE THREAD

**Issue by cfallin** [bytecodealliance/sightglass#102]
I was unable to work out how to collect JSON output into a machine-readable file when running a sequence of `slightglass-cli in-process-benchmark` commands. For now I am grepping through and manually cleaning up a transcript of stdout/stderr -- but this is far from ideal. Would it be possible to either add an option to write output to a particular file, or document this if there is already a way?

**Comment by abrown** [comment]
Let's implement this with some form of `--out-file` flag for the `benchmark` command.
