### ISSUE TITLE
Use the median instead of/in addition to the average

### ISSUE THREAD

**Issue by bnjbvr** [bytecodealliance/sightglass#106]
The average isn't a *stable* statistical measurement. (Whenever Bill Gates enters a very crowded bar, everyone in this bar becomes a billionaire on average.)

It would be nice to add the median value to the set of benchmarking results, since it tends to be more stable overall.

**Comment by fitzgen** [comment]
I think it is fine to include median, but if you're interested in the plans for more rigorous statistical analysis, see the RFC: https://github.com/bytecodealliance/rfcs/blob/main/accepted/benchmark-suite.md#analysis
