### ISSUE TITLE
Prettify JSON output

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/sightglass#110]
It might be nice to have an option for prettifying the JSON output for those who don't have `jq` installed, e.g.

**Comment by fitzgen** [comment]
I think perhaps this isn't necessary given that #131 gives a nice option if you want human-readable output and JSON/CSV can be reserved for machine-readable outputs?

**Comment by abrown** [comment]
Yeah, that makes sense... but IIRC this isn't really my request: I think @bnjbvr or @alexcrichton made a comment about this when you presented a demo? (I should have CCed whoever made the comment). I'm fine closing this with #131 if they are.

**Comment by bnjbvr** [comment]
I can't recall if I was the one asking for this, but yeah, I'd be imagining to be in one of these two settings:

- either I want to get the whole picture, and just having human-readable output is sufficient
- or I want to filter out some results/benchmarks, in which case I can probably use `jq` or any other similar tool and the pretty-printing comes for free with `jq`

So agreed it would be less important to me to get pretty-printing here.
