### ISSUE TITLE
Allow passing paths to wasmtime repo checkouts as engines

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/sightglass#123]
Right now we allow either

* the path to a `libwasmtime_bench_api.{so,dll,dylib}` shared library
* a URL to a hosted git repo that we can `git clone`

to be passed as engines to `sightglass-cli benchmark`.

We should also allow paths to wasmtime repo checkouts on the local file system.

The second option above would normally work for this, except that the `git clone` from inside a docker container, so we don't have access to that part of the filesystem. Also, re-cloning locally is kinda ridiculous since it would uselessly copy a bunch of files and also force a clean build when we could otherwise do a nice incremental build.

**Comment by abrown** [comment]
The "build the engine in Docker" was removed in #170 and one can build the Wasmtime engine using a URL as described [here](https://github.com/bytecodealliance/sightglass/tree/main/engines/wasmtime#use):

```
rustc build.rs
REPOSITORY=https://github.com/<user>/wasmtime REVISION=<hash|branch|tag> ./build
```
