### ISSUE TITLE
Allow building engine to ordinary file, and specifying ordinary file as engine for run

### ISSUE THREAD

**Issue by cfallin** [bytecodealliance/sightglass#128]
This feature request needs some background: I'm currently working on the [new regalloc](https://github.com/bytecodealliance/regalloc2), and am wanting to use Sightglass to measure the impact of each possible feature or heuristic tweak as I make it. This is fairly fine-grained work that ideally benefits from a tight feedback loop; unfortunately, the current best practice for Sightglass has quite a lot more overhead than a "build wasmtime locally and measure `bz2` runtime 5 times with `time`" approximate test I'm using now:

- Sightglass can build an engine based on a git repo and a branch/commit for `wasmtime`;
- `wasmtime` depends on `regalloc.rs`, and `regalloc.rs` provides a shim for the new regalloc and then pulls in `regalloc2`;
- The `main`-branch version of `wasmtime` refers to deps on crates.io, but for local development, I hack `Cargo.toml` files so that my `wasmtime` checkout refers to `regalloc.rs` refers to `regalloc2` all in sibling directories;
- So to get Sightglass to build an engine with the new configuration, I would need to: (i) commit my regalloc2 experiment (possibly just a tweak to a constant in some heuristic) and push to GitHub; (ii) adjust `Cargo.toml` in regalloc.rs to refer to this new commit hash, commit that, and push that to GitHub; (iii) adjust `Cargo.toml` in `cranelift-codegen` to refer to the new regalloc.rs commit, commit that, and push that to GitHub; (iv) use *that* commit hash to ask Sightglass to build a new engine file.

The above gets even more fun if I try to use Cranelift settings to control experiment knobs: I would need to alter the defaults in `cranelift-codegen`, and commit that. If I have `n` regalloc2 variants and `m` different knob settings, I need to make `n*m` separate commits and push them all to GitHub.

The config-knob issue is separate (#103) so let's focus on the separate-versions-of-engine-code problem below.

IMHO, there is a possibly much easier way: we could make the tool fit into the same workflow that someone doing local testing of any other sort would do, and (i) build an artifact from the code on disk, and (ii) test that artifact.

Concretely, this means that Sightglass would (in this mode at least) no longer manage its own cache of engine `.so`s. Instead, it would have some command (for example):

```
$ # (make some tweaks to wasmtime/regalloc2/regalloc.rs source in local checkouts)
$ sightglass-cli compile-engine wasmtime ../../path/to/wasmtime -o wasmtime-variant1.so
```

Then just test using that file explicitly:

```
$ sightglass-cli run -f wasmtime-variant1.so ...
```

This sidesteps all of the questions of syntax for repository paths, what unique name (the "slug" as the source calls it) to use for the engine, etc., and fits much more nicely into the usual Unix tool ecosystem, IMHO; there is no hidden state to worry about.

Then, the infrastructure to build a canonical version of an engine from a clean git checkout with a Dockerized hermetic build could be built on top of this, and used by whatever CI infrastructure we have.

Thoughts?

**Comment by fitzgen** [comment]
You can pass the path to a `libwasmtime_bench_api.so` as an argument to `-e`, so I think everything you want here ~basically works?

Build the `.so` for `main` once:

```
$ cd wasmtime
$ git checkout main
$ cargo build --release -p wasmtime-bench-api
$ cp target/release/libwasmtime_bench_api.so ~/scratch/control.so
```

And then your tight dev loop would look like:

```
$ # make edits
$ cargo build --release -p wasmtime-bench-api
$ sightglass-cli benchmark -e ~/scratch/control.so -e ~/wasmtime/target/release/libwasmtime_bench_api.so ...
```

**Comment by cfallin** [comment]
Oh, neat! Fastest way to learn about an existing feature is to post a feature request for it, I suppose. Thanks :-)

**Comment by fitzgen** [comment]
(You'd probably also want to run `sightglass-cli effect-size` on those benchmark results to get accurate statistics on the difference between means for each engine and the confidence interval on that difference. I want to make this simpler by having a `sightglass-cli benchmark` mode that, rather than dumping the raw results, automatically analyzes them and prints the results to the terminal. This still needs to be done, but you can probably write a ~5 line shell script to encapsulate re-building, re-benching, and re-analyzing in the mean time.)
