### ISSUE TITLE
Add a regex benchmark

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/sightglass#216]
I recently heard someone mention that there is a general assumption that "regex is slow in Wasm." This seems something that could be evaluated by sightglass so I started considering how one might structure such a benchmark: we would want to search for both simple and complex patterns, in small and large texts, with many matches and no matches, etc.

Does anyone know of such a benchmark that already exists? Or, alternately, is there a preference for how such a benchmark should be written? I was thinking it would be easiest to write some Rust code using the `regex` crate and compile it to WebAssembly and then compare this against its native execution. Any other opinions?

**Comment by fitzgen** [comment]
Wizer has a couple regex benchmarks, not sure if there are better ones.

https://github.com/bytecodealliance/wizer/tree/main/benches/regex-bench

https://github.com/bytecodealliance/wizer/tree/main/benches/uap-bench

**Comment by fitzgen** [comment]
Note that those are mostly benchmarking regex construction rather than regex interpretation.
