### ISSUE TITLE
Getting performance counters to work

### ISSUE THREAD

**Issue by matsbror** [bytecodealliance/sightglass#257]
In a previous issue I reported that I found cycle times of sightglass to be magnitudes longer on x86 compared to ARM and RISCV. I then want to use performance counters instead, but get only 0 results. I made sure that the test in `counters.rs` reports some data so I know that the interface works. But when I run a benchmark all I get is:
```
compilation
  benchmarks/blake3-scalar/benchmark.wasm
    cache-accesses
      [0 0.00 0] engines/wasmtime/libengine.so
    cache-misses
      [0 0.00 0] engines/wasmtime/libengine.so
    cpu-cycles
      [0 0.00 0] engines/wasmtime/libengine.so
    instructions-retired
      [0 0.00 0] engines/wasmtime/libengine.so
``` 

Any pointers to what could be the cause of this?

**Comment by matsbror** [comment]
I have tracked down the issue to the recording of the performance counter values. The `end` function records some values here:
![image](https://github.com/bytecodealliance/sightglass/assets/10210145/97bba18d-d4b3-4588-b700-5170c5516966)
and here are the values:
![image](https://github.com/bytecodealliance/sightglass/assets/10210145/835231ea-3087-449a-8c7c-61b6dfe8631a)

However, when indexed with the reference counter, it returns zero passed to the `add` method.
But when

**Comment by abrown** [comment]
I don't get a great sense for what is going wrong here: does the `perf-counters` measure work on x86 but not on some other architecture? Is your sense that there is a problem with the `perf_event` crate, e.g., [here](https://github.com/bytecodealliance/sightglass/blob/04546548e60dcce4b6691f8ddb75442c4d251ad9/crates/recorder/src/measure/counters.rs#L76)? How would one replicate this?

**Comment by matsbror** [comment]
I am going to close this now. When I used `--pin` performance counters returned all 0, when I removed it, the counters worked.

**Comment by abrown** [comment]
Ok, maybe there's something wrong with the `core_affinity` crate, which does this work, or maybe we're using it wrong. Looking at [`bind_to_single_core`](https://github.com/bytecodealliance/sightglass/blob/04546548e60dcce4b6691f8ddb75442c4d251ad9/crates/recorder/src/cpu_affinity/affinity_core_affinity.rs#L4) it appears that we are trying to change the affinity to the last available core ID. Maybe this has some interaction with `perf`? (I would have thought this would be fine). The reason I never see this is that I usually run sightglass under something like `taskset --cpu-list ...`, which I have had better luck with.
