### ISSUE TITLE
Test docker containers in CI

### ISSUE THREAD

**Issue by jlb6740** [bytecodealliance/sightglass#30]
For the future: I really wish this were running in CI; it's very difficult to know what effect these changes will have without downloading the branch and running the thing on my system. There's no reason that GitHub actions couldn't do this, right?

_Originally posted by @abrown in https://github.com/bytecodealliance/sightglass/pull/26#issuecomment-660225425_

**Comment by abrown** [comment]
Closing this; I think this no longer applies.
