### ISSUE TITLE
Clean script to pull get projects (clean submodule update)

### ISSUE THREAD

**Issue by jlb6740** [bytecodealliance/sightglass#33]
Yes ... it is the same for other VMs though and not specific to enabling wamr. I was working on a separate cleanup patch to do this across all git downloads consistently while also cleaning up a bunch of other things.

_Originally posted by @jlb6740 in https://github.com/bytecodealliance/sightglass/pull/28#discussion_r460643913_

**Comment by abrown** [comment]
@jlb6740, I think this can be closed? Re-open if I'm wrong...
