### ISSUE TITLE
Refactor wrapper script to reduce the potential for overhead of snprintf call

### ISSUE THREAD

**Issue by jlb6740** [bytecodealliance/sightglass#34]
👍 Ahh, yes, maybe. Unless there is something about these preprocessor directives that won't allow this. If there is no issue this is probably a good idea. Like some of the other comments, this will apply generally so we can test this out in a future patch that applies consistently in all wrappers.

_Originally posted by @jlb6740 in https://github.com/bytecodealliance/sightglass/pull/28#discussion_r460662635_

**Comment by abrown** [comment]
This code is now gone as of https://github.com/bytecodealliance/sightglass/pull/181.
