### ISSUE TITLE
sightglass next: Support for multiple input workloads

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/sightglass#70]
After chatting with @abrown we came up with the following extension to the benchmark program protocol to support multiple input workloads (eg a "default" workload and a "small" workload that is used for quickly testing an idea):

* the runner has a `--small-workload` flag
* this sets a `WASM_BENCH_USE_SMALL_WORKLOAD=1` environment variable for benchmark programs
* the directory where the wasm benchmark program lives is preopened for its execution
* the wasm benchmark program may read that env var and use that to decide which input files to read and process as its workload

Example:

```
fn main() {
    let workload = if std::env::var("WASM_BENCH_USE_SMALL_WORKLOAD").is_ok() {
        read_small()
    } else {
        read_default()
    };
    bench_start();
    process(workload);
    bench_end();
}
```

Things to note:

* benchmarks can ignore the env var if they have only a single workload and it Just Works (eg micro benchmarks)
* easier to implement in runner than a stdin protocol, work is pushed to benchmark programs themselves, and it is easier for them then the runner
* flexible for situations where a workload is made up of multiple files, where as stdin would require some sort of JSON wrapping of them or something
* easy to add new env vars in the future for new extension points, if needed

**Comment by abrown** [comment]
@fitzgen, isn't this complete?

**Comment by fitzgen** [comment]
Yes, although not all benchmarks take advantage of it (which is fine).
