### ISSUE TITLE
sightglass-next: add a format option for Markdown

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/sightglass#97]
In order to display tables of significant performance changes, we discussed creating a Markdown table from the analyzed data. Here is a proposed table:

```
| Benchmark      | Phase       | Event                | `main` (SHA: `0123456`) | PR #42 (SHA `abcdef2`) | Significant Change  |
|----------------|-------------|----------------------|-------------------------|------------------------|---------------------|
| shootout-fib2  | Execution   | cycles               | 100,000,000             | 110,000,000            | -10%                |
| shootout-gimli | Compilation | instructions-retired | ...                     | ...                    | +2%                 |
| ...            | ...         | ...                  | ...                     | ...                    | ...                 |
```

**Comment by abrown** [comment]
Since the runner already has some understanding of output formats, I propose we just add the Markdown code here. Splitting it out to the CI action creates more places where things can break (vs. testing them all in this repository) and others may find Markdown output useful.

I agree that the ultimate goal of this issue is to render only significant results but I was planning to start working on this now--so we would have to render all results. Then when #89 is finished we can render the correct subset? I guess what I'm saying is that "rendering to Markdown" and "rendering only significant results" don't _need_ to depend on each other.

**Comment by fitzgen** [comment]
My concern is that markdown isn't a data format, like json and csv are, it is a presentation language.

This means that if we want to tweak how tables look in the github bot, we'll be tweaking the benchmark runner's code, which seems like we are mixing up concerns.

IMO, the sightglass cli should only deal with data, not presentation. E.g. it should add a is-this-significant? bool to each row in our analysis results, but it shouldn't remove actively remove rows of data (deciding what is or is not shown is a presentation concern, and we might not want to fully *remove* but just *hide behind a `<details>`*, etc and all this logic should be in the github bot not the sightglass cli).

> I guess what I'm saying is that "rendering to Markdown" and "rendering only significant results" don't _need_ to depend on each other.

Agreed on this.

**Comment by abrown** [comment]
Ok, sounds like this issue should be filed somewhere else then. Let's close and you can work on this in the Wasmtime CI when you have a chance.
